version: "3.6"

networks:
  publicationmapper:

services:
  web:
    build: .
    image: "pabloscolpino/publication-mapper:latest"
    depends_on:
      - db
    networks:
      - publicationmapper
    ports:
      - "23000:3000"
    command: bundle exec puma -C config/puma.rb
    env_file:
      - ./.env
    volumes:
      - .:/app:cached
      - bundler:/bundler:cached
      - node_modules:/app/node_modules:cached
    environment:
      DATABASE_URL: postgres://postgres@db/pubmap_dev
      TEST_DATABASE_URL: postgres://postgres@db/pubmap_test

  db:
    image: postgres:9.6.15
    networks:
      - publicationmapper
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: pubmap

volumes:
  pg-data:
  bundler:
  node_modules:
